ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 0

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "Main Fort and neighbors"
file = "images/main_fort.png"
startx = 0
starty = 429
priority = 3

[[structure]]
name = "r/autism"
file = "images/autism.png"
startx = 250
starty = 1850
priority = 2
