ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 0

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "Main Fort and Allies"
file = "images/fort_temple.png"
startx = 0
starty = 464
priority = 3
